logging:
  level:
    org.springframework.boot.orientdb.hello: debug
---
server:
  port: 8780
  servlet:
    context-path: /orientServices
---
spring:
  main.allow-bean-definition-overriding: true
---
spring:
  thread:
    maxPoolSize: 8
    corePoolSize: 4
  data:
    orient:
      url: remote:10.200.101.223:2424/inventory
      username: root
      password: root