/*
 * This file is generated by jOOQ.
 */
package org.springframework.boot.orientdb.hello;


import javax.annotation.Generated;

import org.springframework.boot.orientdb.hello.tables.Person;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.PERSON</code>.
     */
    public static final Person PERSON = org.springframework.boot.orientdb.hello.tables.Person.PERSON;
}
